import esbuild from "esbuild";
import process from "process";
import { copyFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// In dev mode, output directly to vault for hot reload
// In prod mode, output to dist/ directory
const outfile = prod
    ? "dist/main.js"
    : "../example-vault/.obsidian/plugins/obsidian-spark/main.js";

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: outfile,
});

if (prod) {
    await context.rebuild();
    // Copy static files to dist/ for production
    copyFileSync("manifest.json", "dist/manifest.json");
    copyFileSync("styles.css", "dist/styles.css");
    console.log("✅ Production build complete in dist/");
    process.exit(0);
} else {
    // Copy static files to vault in dev mode
    copyFileSync("styles.css", "../example-vault/.obsidian/plugins/obsidian-spark/styles.css");
    copyFileSync("manifest.json", "../example-vault/.obsidian/plugins/obsidian-spark/manifest.json");
    console.log("🔥 Dev mode active - watching for changes...");
    await context.watch();
}

